spring:
  profiles:
    active: @profiles.active@
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      aop-patterns: com.btc123.app.service
      filter: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      min-idle: 5
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
        allow: 127.0.0.1
  aop:
    proxy-target-class: true
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
jsondoc:
  version: 1.0
  packages[0]: com.btc123.app.model
  packages[1]: com.btc123.app.controller
  displayMethodAs: SUMMARY
  playgroundEnabled: true
#自定义参数
captchaLimit: 10
#行情http连接ip
ip: http://market.bosha.com:9092
#ip: http://127.0.0.1:8084